-Added difficulty level buttons nested within 1P mode button.
EECS-581-Cool-Kids/Battleship-Project-2 pull request #15
Opened 2024-09-25 15:42 UTC by Platnumrcn14

**homeScreen.html**
-Implemented a difficulty selector option nested in the 1P mode button of the main menu
![2024-09-25](https://github.com/user-attachments/assets/2e3fe4d7-9797-4951-b539-414e2542ff02)
 
![2024-09-25 (6)](https://github.com/user-attachments/assets/5f15e61c-a52d-4ce7-9d61-d84fa00054ed)

**server.js**
-created the framework for homeScreen.html to communicate the difficulty option selected to the server.js
![2024-09-25 (1)](https://github.com/user-attachments/assets/3d8d749c-6ab0-4b5e-a5be-6ace8f1cbc67)

**battleshipRound.js**
-Implemented Hard mode for AI that will iterate through the game board for a hittable grid position. Once found will hit that position. 
-Medium mode nested within easy mode
![2024-09-25 (5)](https://github.com/user-attachments/assets/2aa64f00-f6aa-4b96-a1b2-c728f4faeaed)
![2024-09-25 (7)](https://github.com/user-attachments/assets/031142ce-4d54-404f-b29f-a2e57cb018f2)

2024-09-25 17:10 UTC, jacobwilki01 requested changes

2024-09-25 17:10 UTC, jacobwilki01 commented on back/server/server.js
>          // TODO: ALLOW SPECIFYING DIFFICULTY
remove todo comment

2024-09-25 17:10 UTC, jacobwilki01 commented on front/homeScreen/homeScreen.html
why;d you change the spacing of this file so much?

2024-09-25 17:10 UTC, jacobwilki01 commented on back/server/modules/battleshipRound.js
> +    targetNextShipTile(opMap) {
this is an inefficient way of doing this. Your current implementation has us iterate through the grid **every single time** its the AI's turn, and checks tiles we know are hit already.

Instead, lets generate a list of "tiles to hit" at the start of the first AI turn that is stored in this class. Then, whenever its the AI's turn, grab the next item in the list, remove it from the list, and return that tile.

2024-09-25 17:58 UTC, eBerkley approved these changes
Looks good to me.

2024-09-26 16:49 UTC, jacobwilki01 approved these changes

2024-09-26 16:49 UTC, jacobwilki01 commented on back/server/modules/battleshipRound.js
> +        // If the target list is empty, we need to scan the grid and populate it
Let's invert the order of these. So:

if (this.aiTargetList.Length > 0) {
  return this.aiTargetList.shift();
}

THEN generate the list and return the first value. That removes the need for the length check of 0 and some of the nesting.

2024-09-28 21:09 UTC, richardmoser approved these changes

2024-09-29 04:25 UTC, modmo22 approved these changes
Looks great!

2024-09-29 04:27 UTC, merged